deschedulerPolicy:
  profiles:
    - name: descheduler-policy
      pluginConfig:
        - name: "RemovePodsViolatingNodeAffinity"
          args:
            nodeAffinityType:
              - "preferredDuringSchedulingIgnoredDuringExecution"
      plugins:
        deschedule:
          enabled:
            - "RemovePodsViolatingNodeAffinity"
