apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: oci://ghcr.io/nginx/charts/nginx-ingress
      chart: nginx-ingress
      targetRevision: 2.4.1
      helm:
        valueFiles:
          - $values/nginx-ingress/values.yaml
    - repoURL: https://github.com/byulmaru/infrastructure.git
      targetRevision: HEAD
      ref: values
      path: nginx-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
