controller:
  image:
    repository: docker.io/nginx/nginx-ingress
  service:
    externalTrafficPolicy: Cluster
    annotations:
      oci.oraclecloud.com/load-balancer-type: "nlb"
      service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "1000"
      oci-network-load-balancer.oraclecloud.com/is-ppv2-enabled: "true"
  config:
    entries:
      proxy-protocol: "true"
      http2: "true"
