operatorConfig:
  image:
    repository: docker.io/tailscale/k8s-operator
proxyConfig:
  image:
    repository: docker.io/tailscale/tailscale
oauthSecretVolume:
  secret:
    secretName: oauth-client-credentials
apiServerProxyConfig:
  mode: "true"
